### ISSUE TITLE
Traducción vista exportación census no funciona

### ISSUE THREAD

**Issue by DiegoRuizGil** [Villanueva-del-Trabuco-EGC/decide-part-1#16]
La traducción de la vista /census/export/<id_votación> no funciona correctamente. La vista se corresponde con el siguiente html:
census/templates/export_census.html, específicamente las etiquetas 'vName' de la línea 16 y 'vDesc' de la ínea 17.
@TheNeoStormZ @Framigdom

**Comment by Framigdom** [comment]
Actualiza con master (Villanueva-Trabuco-decide-part-1) tu rama, que ya estan los cambios subidos en el repositorio global. Solo habia que importarle la libreria y el archivo .po que parece que no estaba bien importado. De igual forma si actualizas con el global deberia ir bien.
Si sigue persistiendo el error despues de actualizarlo, no dudes en avisarme de nuevo.

**Comment by TheNeoStormZ** [comment]
Si el consejo de @Framigdom no te funciona, prueba a ejecutar los siguientes comandos en la terminal de tu distro linux:

django-admin makemessages
django-admin compilemessages

Si los comandos anteriores no funcionan, es posible que necesites instalar un paquete extra, gettext.

Usa "sudo apt-get install gettext" si tu distro es Ubuntu/Debian o basado en esta.

**Comment by DiegoRuizGil** [comment]
Perfecto, con los comandos ya me realiza bien la traducción.
