### ISSUE TITLE
Error de traducción en archivo template_activate_account.html

### ISSUE THREAD

**Issue by TheNeoStormZ** [Villanueva-del-Trabuco-EGC/decide-part-1#24]
Es necesario añadir la linea {% load i18n static %} para importar la tag "trans" necesaria, de lo contrario, se devuelve un error de servidor 500.

**Comment by Framigdom** [comment]
Tienes razon pero me he dado cuenta que hacer traducciones en ese html puede que ocasione errores ya que ese archivo esta hecho para cuando te notifica al correo. Por tanto, tengo pensado poner el texto en ingles como idioma estandar para las notificaciones de los correos.¿Que te parece?

Adjunto tambien a @javmarjae porque al hacer el register no me sale mi user.username, por si puede solucionarlo.

**Comment by javmarjae** [comment]
Se va a corregir para que no llame a cada usuario por su nombre. En su lugar, todos serán conocidos como "Deciders".
