### ISSUE TITLE
Census Traduccion

### ISSUE THREAD

**Issue by Framigdom** [Villanueva-del-Trabuco-EGC/decide-part-1#33]
Abro esta issue para comunicarme con @DiegoRuizGil para que el texto del formulario sea accesible desde el html para que se pueda realizar la traduccion.

**Comment by DiegoRuizGil** [comment]
El texto que aparece en el formulario para elegir los atributos puedo separarlo del form de django y añadirlo en el propio html. En cuanto a los nombre de los atributos, creo que va a ser imposible que se realice la traducción ya que los extraigo directamente desde la clase User y se los añado como valores al objeto formulario.

**Comment by DiegoRuizGil** [comment]
Ya he creado el pull request con el cambio necesario para realizar la traducción.
