### ISSUE TITLE
Fallo en el merge de develop hacia decide-part-1 (master)

### ISSUE THREAD

**Issue by Dr-Vell** [Villanueva-del-Trabuco-EGC/decide-part-1#34]
Hay problemas con los test de visualizer, booth y census. 
Deberíamos arreglarlos cuanto antes para poder continuar con la integración en el repositorio conjunto.

**Comment by DiegoRuizGil** [comment]
Yo tengo un test en la clase ExportCensusTestCase (test_census_utils), ¿da algún fallo ese test?

**Comment by TheNeoStormZ** [comment]
Se ha creado una pull que intenta arreglar los tests despues del merge

**Comment by Dr-Vell** [comment]
@DiegoRuizGil Al parecer era un problema con las traducciones al hacer merge, ya está arreglado el census tests.

**Comment by TheNeoStormZ** [comment]
Ahora fallan tus test @DiegoRuizGil y los mios, deberiamos mirarlo en conjunto
