### ISSUE TITLE
Fallo en los actions por los test de Ingles

### ISSUE THREAD

**Issue by Framigdom** [Villanueva-del-Trabuco-EGC/decide-part-1#56]
Parece que me da fallo al subir los test en ingles al master, en local(mi maquina) va bien pero no se porque parece que al subirlo falla y daña otros test tambien de algunos compañeros,¿alguna sugerencia de que hacer?

Creo que puede ser por la ruta que se usa para usar los test que uso "http://127.0.0.1:8000/visualizer/1/" porque si ya esta creado, dentro del test el boton funciona y cambia de idioma. En cambio, si creo un votacion nueva y le paso su id, parece que el boton no funciona y no reconoce el idioma en ingles. No se porque sucede esto, como funcionalidad cuando lo cambias va bien y si usas la extension de chrome de seleniunIDE tambien funciona pero en codigo parece que cuando crea la votacion "crashea" o no le gusta algo que hace que el idioma no lo reconozca y se ponga por defecto. Es por ello que puse la ruta mencionada al principio y funcionaba bastante bien.

Se podria intentar en master tener el id de una votacion ya creada y ponerla sobre esa ruta y alomejor funciona(lo unico que se me ocurre), sino funcionase¿Que se podria hacer?

**Comment by DiegoRuizGil** [comment]
Prueba a realizar el formulario de selección de idioma con un formulario de Django. Puede que con eso sea más fácil procesar la información en la vista.

**Comment by Framigdom** [comment]
¿Podemos verlo entre los dos y me explicas mas concretamente?

**Comment by DiegoRuizGil** [comment]
Venga

**Comment by Framigdom** [comment]
Ya esta solucionado, gracias.
Cierro la issue.
