### ISSUE TITLE
Fallo en workflow de master - decide part 1

### ISSUE THREAD

**Issue by Dr-Vell** [Villanueva-del-Trabuco-EGC/decide-part-1#61]
Con la adición de los tests de traducción al inglés, están fallando los test de traducción de census.
Parece que al cambiar la configuración al inglés se mantiene para otros tests los cuales no tienen este cambio previsto.
Deberíamos arreglarlo cuanto antes para poder continuar con el trabajo de traducción pendiente.

**Comment by TheNeoStormZ** [comment]
Parece que el problema radica en que se esta cambiado al inglés en algunos tests y despues en su tearDown correspondiente no se cambia al idioma por defecto

@Framigdom creo que es mas eficiente modificar los tearDown que has hecho antes que todos los demas setUp

**Comment by Framigdom** [comment]
Si, puede que sea eso. Voy a comprobarlo
