### ISSUE TITLE
Error en la badge del workflow que aparece en README.md

### ISSUE THREAD

**Issue by Dr-Vell** [Villanueva-del-Trabuco-EGC/decide-part-1#62]
Hace falta cambiar las badges que aparece en el readme ya que hacen referencia a otro repositorio por error.

edit: pasa lo mismo con las tres badges

**Comment by TheNeoStormZ** [comment]
Propongo actualizar las badges para que apuntel al decide global, que al final es el que se va a utilizar en conjunto
